nome = input('Digite seu nome completo: ').strip()
print('Analisando seu nome...')
print('Seu nome em maiusculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
#print('Seu nome tem ao todo {} letras'.format(len(''.join(nome.split()))))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
#primeiroNome = nome.split()
#print(len(primeiroNome[0]))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))

